#!/usr/bin/env npx tsx
/**
 * FusionClaw Onboarding Script
 * Interactive setup wizard for new installations
 *
 * Usage: npm run onboard
 */

import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

// ANSI color codes
const colors = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  amber: "\x1b[38;5;214m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  gray: "\x1b[90m",
};

// ASCII Art Banner
const BANNER = `
${colors.amber}${colors.bright}
   ███████╗██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗
   ██╔════╝██║   ██║██╔════╝██║██╔═══██╗████╗  ██║
   █████╗  ██║   ██║███████╗██║██║   ██║██╔██╗ ██║
   ██╔══╝  ██║   ██║╚════██║██║██║   ██║██║╚██╗██║
   ██║     ╚██████╔╝███████║██║╚██████╔╝██║ ╚████║
   ╚═╝      ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝
${colors.cyan}                       CLAW${colors.reset}

${colors.dim}   Your Business-in-a-Box for AI Agents${colors.reset}

`;

// Helper to generate API key
function generateApiKey(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let key = "fusionclaw_sk_live_";
  for (let i = 0; i < 32; i++) {
    key += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return key;
}

// Create readline interface
function createPrompt(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

// Ask a question
function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

// Print with color
function print(text: string, color: string = colors.reset) {
  console.log(`${color}${text}${colors.reset}`);
}

// Print success message
function success(text: string) {
  console.log(`${colors.green}✓${colors.reset} ${text}`);
}

// Print error message
function error(text: string) {
  console.log(`${colors.red}✗${colors.reset} ${text}`);
}

// Print info message
function info(text: string) {
  console.log(`${colors.cyan}ℹ${colors.reset} ${text}`);
}

// Main onboarding flow
async function main() {
  console.clear();
  console.log(BANNER);

  const rl = createPrompt();
  const projectRoot = path.resolve(__dirname, "..");
  const envPath = path.join(projectRoot, ".env.local");

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    print("\n  An existing .env.local file was found.", colors.amber);
    const overwrite = await ask(rl, `${colors.gray}  ? ${colors.reset}Overwrite existing configuration? (y/N): `);
    if (overwrite.toLowerCase() !== "y") {
      print("\n  Onboarding cancelled. Your existing configuration is unchanged.", colors.dim);
      rl.close();
      process.exit(0);
    }
    print("");
  }

  print("  Let's get your FusionClaw instance set up.\n", colors.dim);

  // Collect configuration
  print("  " + "─".repeat(50), colors.dim);
  print("  DATABASE CONFIGURATION", colors.bright);
  print("  " + "─".repeat(50), colors.dim);

  const databaseUrl = await ask(
    rl,
    `\n${colors.gray}  ? ${colors.reset}Enter your Neon DATABASE_URL:\n${colors.dim}    (postgresql://user:pass@host/db?sslmode=require)${colors.reset}\n    > `
  );

  if (!databaseUrl.startsWith("postgresql://")) {
    error("  Invalid DATABASE_URL format. Should start with 'postgresql://'");
    rl.close();
    process.exit(1);
  }

  print("\n  " + "─".repeat(50), colors.dim);
  print("  AI SERVICES", colors.bright);
  print("  " + "─".repeat(50), colors.dim);

  const openrouterKey = await ask(
    rl,
    `\n${colors.gray}  ? ${colors.reset}Enter your OpenRouter API key ${colors.dim}(optional, press Enter to skip)${colors.reset}:\n    > `
  );

  const falKey = await ask(
    rl,
    `\n${colors.gray}  ? ${colors.reset}Enter your fal.ai key ${colors.dim}(optional, press Enter to skip)${colors.reset}:\n    > `
  );

  // Generate MCP API key
  const mcpApiKey = generateApiKey();

  // Build .env.local content
  const envContent = `# FusionClaw Configuration
# Generated by: npm run onboard
# Date: ${new Date().toISOString()}

# Neon PostgreSQL
DATABASE_URL=${databaseUrl}

# OpenRouter (AI Chat / Humanizer)
OPENROUTER_API_KEY=${openrouterKey || "# Not configured"}

# fal.ai (Image Generation)
FAL_KEY=${falKey || "# Not configured"}

# MCP Server (Agent Access)
# This key grants full access to the platform via MCP
MCP_API_KEY=${mcpApiKey}

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

  // Write .env.local
  print("\n  " + "─".repeat(50), colors.dim);
  print("  SETTING UP YOUR INSTANCE", colors.bright);
  print("  " + "─".repeat(50) + "\n", colors.dim);

  try {
    fs.writeFileSync(envPath, envContent);
    success("Environment configured (.env.local created)");
  } catch (err) {
    error(`Failed to write .env.local: ${err}`);
    rl.close();
    process.exit(1);
  }

  // Run database migration
  info("Running database migration...");
  try {
    execSync("npx drizzle-kit push --force", {
      cwd: projectRoot,
      stdio: "inherit",
      env: { ...process.env, DATABASE_URL: databaseUrl },
    });
    success("Database schema migrated");
  } catch (err) {
    error("Database migration failed. Check your DATABASE_URL.");
    info("You can run 'npm run db:push' manually after fixing the connection.");
  }

  // Display success message
  print("\n  " + "═".repeat(50), colors.amber);
  print(`${colors.green}${colors.bright}  Your FusionClaw instance is ready!${colors.reset}\n`);

  print(`  ${colors.bright}Your MCP API Key:${colors.reset}`);
  print(`  ${colors.cyan}${mcpApiKey}${colors.reset}\n`);

  print(`  ${colors.dim}Keep this key secret! It grants full platform access.${colors.reset}\n`);

  print("  " + "─".repeat(50), colors.dim);
  print("  NEXT STEPS", colors.bright);
  print("  " + "─".repeat(50) + "\n", colors.dim);

  print(`  ${colors.bright}Start the web UI:${colors.reset}`);
  print(`  ${colors.cyan}  npm run dev${colors.reset}\n`);

  print(`  ${colors.bright}Start the MCP server (for AI agents):${colors.reset}`);
  print(`  ${colors.cyan}  npm run mcp${colors.reset}\n`);

  print(`  ${colors.bright}Connect Claude Code:${colors.reset}`);
  print(`  ${colors.dim}  Add to ~/.claude/mcp_servers.json:${colors.reset}`);
  print(`  ${colors.cyan}  {
    "fusionclaw": {
      "command": "node",
      "args": ["${projectRoot}/mcp-server/dist/index.js"],
      "env": { "MCP_API_KEY": "${mcpApiKey}" }
    }
  }${colors.reset}\n`);

  print("  " + "═".repeat(50) + "\n", colors.amber);

  rl.close();
}

main().catch((err) => {
  console.error("Onboarding failed:", err);
  process.exit(1);
});
